/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/cloud/scene.gltf 
Author: RandyGF (https://sketchfab.com/RandyGF)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-3a76eb255e3c4c0199bbfedb2b54342f
Title: Cloud
*/

import React, { memo, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'

const Scene = memo(function Scene(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  
  return useMemo(() => (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Cloud} scale={0.5} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Cloud} scale={0.5} />
      <ambientLight intensity={0.5} />
      <directionalLight position={[10, 10, 5]} intensity={1} />
    </group>
  ), [props, nodes, materials])
})

useGLTF.preload('/scene.gltf')
export default Scene;
